---
lang: fr
---
# Introduction 
<!-- ```{r}
#| echo: false
#| results: "asis"

source("../../_common.R")
status("review")
``` -->

<!-- ## Aperçu -->

Cette section présente les concepts fondamentaux de MOSAIKS (Multi-task Observation using Satellite Imagery & Kitchen Sinks) et fournit des conseils pratiques pour commencer à l'utiliser. Que vous soyez nouveau dans l'analyse des images satellites ou un praticien expérimenté, la compréhension de ces fondements est cruciale pour utiliser efficacement MOSAIKS dans votre travail.

MOSAIKS comble le fossé entre le vaste potentiel de l'imagerie satellite et les applications pratiques en fournissant des: 

- Outils d'apprentissage automatique accessibles pour les non-experts
- Prédictions peu coûteuses en temps de calcul
- Applications flexibles dans diverses tâches
- Solutions qui peuvent être mise à l'échelle pour répondre à des défis mondiaux

## Quand utiliser MOSAIKS?

MOSAIKS est particulièrement précieux lorsque vous avez besoin de:

- Générer des prédictions dans de grandes zones géographiques
- Travailler avec des ressources de calcul limitées
- Analyser plusieurs résultats en utilisant la même imagerie
- Créer des prédictions sans utiliser de l'apprentissage profond
- Généraliser des analyses d'une application locale à une application globale

Cependant, MOSAIKS peut ne pas être le meilleur choix lorsque:

- Vous avez besoin de prédictions à une résolution inférieure au kilomètre
- Votre résultat nécessite des bandes spectrales spécifiques
- Les prédictions en temps réel sont essentielles
- Votre application nécessite des features qui sont interprétables

::: {.callout-tip}
Il peut y avoir un [outil existant](https://github.com/satellite-image-deep-learning) qui répond à vos besoins.MOSAIKS n'est pas le meilleur choix pour chaque application.
:::

## Aperçu de la section

Les chapitres suivants vous guideront à travers le démarrage avec MOSAIKS:

| Chapitre | Sujets clés |
|---------|:-----------|
|@sec-intro-compute |Google Colab, Gestion des données, Pratiques de mise en œuvre |
|@sec-intro-mosaiks |Concepts de base, architecture système, capacités |
|@sec-intro-api |Accès à l'API, produits de données, authentification |
|@sec-intro-demo |Workflow de base, analyse d'exemples, pièges communs |

: Aperçu de la section d'introduction {#tbl-section-outline .striped .hover}

Ces chapitres fournissent à la fois la compréhension théorique et les compétences pratiques nécessaires pour commencer à travailler avec MOSAIKS. L'accent est mis sur la mise à disposition des prédictions par satellite tout en maintenant une rigueur scientifique et une efficacité informatique.

::: {.callout-note}
Dans le chapitre suivant, nous allons configurer notre environnement informatique à l'aide de Google Colab. Ce cours utilise Colab pour démontrer divers aspects des MOSAIKS, dans un environnement gratuit et accessible.
:::