# Satellite imagery  {#sec-sat-img}

```{r}
#| echo: false
#| results: "asis"

source("../../_common.R")
status("review_en")
```

## Overview

This section of the book aims to help navigate the complex world of satellite imagery, with a focus on applying these data within the MOSAIKS framework. While MOSAIKS API features are sufficient for many applications, some use cases require working directly with satellite imagery. Understanding how to select and process appropriate imagery becomes crucial in these situations.

::: {.callout-note}
The skills covered in these chapters are primarily relevant for users who need to generate custom MOSAIKS features. If you plan to use the MOSAIKS API features, you can skip this section.
:::

## Section outline

The following chapters will guide you through key considerations when working with satellite imagery:

| Chapter | Key Topics |
|---------|:-----------|
| @sec-satellite-imagery | Resolution types, data sources, selection criteria |
| @sec-satellite-processing | Pre-processing steps, quality control, computing needs |

: Outline of the satellite imagery section {#tbl-section-outline .striped .hover}

These chapters provide practical guidance for incorporating satellite imagery into your MOSAIKS workflow while highlighting important technical and logistical considerations.

::: {.callout-note}
# Looking forward

In the next chapter, we will take a look at how to choose the right satellite imagery for your application.
:::

